version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: nba-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  backend:
    build: .
    container_name: nba-backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NBA_API_TIMEOUT=30
      - LOG_LEVEL=INFO
    depends_on:
      - redis
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    restart: unless-stopped
    command: python start_server.py

  frontend:
    build: ./frontend
    container_name: nba-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  redis_data:
